#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : apriltag
Version  : 0.0.16
Release  : 1
URL      : https://files.pythonhosted.org/packages/f2/e5/957bb26d575141bc25af7214c14e315c9ebb9a12ccf7c8d09ed40b59bb29/apriltag-0.0.16.tar.gz
Source0  : https://files.pythonhosted.org/packages/f2/e5/957bb26d575141bc25af7214c14e315c9ebb9a12ccf7c8d09ed40b59bb29/apriltag-0.0.16.tar.gz
Summary  : apriltag marker detection
Group    : Development/Tools
License  : BSD-3-Clause
Requires: apriltag-bin = %{version}-%{release}
Requires: apriltag-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3

%description
Apriltag
--------
apriltag marker detection
based on <https://github.com/swatbotics/apriltag>

%package bin
Summary: bin components for the apriltag package.
Group: Binaries
Requires: apriltag-license = %{version}-%{release}

%description bin
bin components for the apriltag package.


%package dev
Summary: dev components for the apriltag package.
Group: Development
Requires: apriltag-bin = %{version}-%{release}
Provides: apriltag-devel = %{version}-%{release}
Requires: apriltag = %{version}-%{release}
Requires: apriltag = %{version}-%{release}

%description dev
dev components for the apriltag package.


%package license
Summary: license components for the apriltag package.
Group: Default

%description license
license components for the apriltag package.


%prep
%setup -q -n apriltag-0.0.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1573516929
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1573516929
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/apriltag
cp %{_builddir}/apriltag-0.0.16/LICENSE.md %{buildroot}/usr/share/package-licenses/apriltag/45997de52d34ba2e7b17db8278c031de605359fa
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/apriltag_demo
/usr/bin/maketags

%files dev
%defattr(-,root,root,-)
/usr/lib/libapriltag.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/apriltag/45997de52d34ba2e7b17db8278c031de605359fa
